name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-ghcr-image:
    runs-on: ubuntu-latest
    
    env:
      ORIGIN: https://stacks.hoyt.services

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create env file
        run: |
          touch .env
          echo "ORIGIN=https://stacks.hoyt.services" >> .env
          echo "ENABLE_DRIZZLE_LOGGER=${{ secrets.ENABLE_DRIZZLE_LOGGER }}" >> .env
          echo "POSTGRES_DB_HOST=${{ secrets.POSTGRES_DB_HOST }}" >> .env
          echo "POSTGRES_DB_PORT=${{ secrets.POSTGRES_DB_PORT }}" >> .env
          echo "POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}" >> .env
          echo "POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> .env
          echo "POSTGRES_MAX_CONNECTIONS=${{ secrets.POSTGRES_MAX_CONNECTIONS }}" >> .env
          
          echo "TUNNEL_HOST=${{ secrets.TUNNEL_HOST }}" >> .env
          echo "TUNNEL_USER=${{ secrets.TUNNEL_USER }}" >> .env
          echo "TUNNEL_PORT=22" >> .env
          echo "TUNNEL_PRIVATE_KEY=" >> .env
          echo "TUNNEL_PRIVATE_KEY_PATH=.tunnel_key" >> .env
          echo "TUNNEL_DEST_HOST=${{ secrets.TUNNEL_DEST_HOST }}" >> .env
          echo "TUNNEL_DEST_PORT=${{ secrets.TUNNEL_DEST_PORT }}" >> .env
          echo "TUNNEL_LOCAL_PORT=${{ secrets.TUNNEL_LOCAL_PORT }}" >> .env
          echo "TUNNEL_DEBUG=${{ secrets.TUNNEL_DEBUG }}" >> .env
          
          echo "MYSQL_DB_HOST=${{ secrets.MYSQL_DB_HOST }}" >> .env
          echo "MYSQL_DB_PORT=${{ secrets.MYSQL_DB_PORT }}" >> .env
          echo "MYSQL_DB_USER=${{ secrets.MYSQL_DB_USER }}" >> .env
          echo "MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}" >> .env
          echo "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}" >> .env
          echo "MYSQL_USE_SSH=${{ secrets.MYSQL_USE_SSH }}" >> .env
          
          echo "GITHUB_CLIENT_ID=" >> .env
          echo "GITHUB_CLIENT_SECRET=" >> .env
          echo "GOOGLE_OAUTH_CLIENT_ID=" >> .env
          echo "GOOGLE_OAUTH_CLIENT_SECRET=" >> .env
          echo "GOOGLE_OAUTH_REDIRECT_URI=" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
          echo "FROM_EMAIL=${{ secrets.FROM_EMAIL }}" >> .env
          echo "CMP_CLIENT_ID=${{ secrets.CMP_CLIENT_ID }}" >> .env
          
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}" >> .env
          echo "PUBLIC_SUPABASE_KEY=${{ secrets.PUBLIC_SUPABASE_KEY }}" >> .env
          echo "PUBLIC_POSTHOG_KEY=${{ secrets.PUBLIC_POSTHOG_KEY }}" >> .env
          echo "AUTH_INITIALIZE=false" >> .env
          
          cat .env
          
      - name: Setup SSH key
        run: |
          echo "${{ secrets.TUNNEL_PRIVATE_KEY }}" > .tunnel_key
          chmod 600 .tunnel_key

      - name: Build and push Docker image for Linux
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/drewpayment/stacks:latest
            ghcr.io/drewpayment/stacks:${{ github.sha }}
          build-args: |
            ORIGIN=${{ secrets.ORIGIN }}
