name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-ghcr-image:
    runs-on: ubuntu-latest
    
    env:
      ORIGIN: https://stacks.hoyt.services

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create env file
        run: |
          touch .env
          echo "ORIGIN=https://stacks.hoyt.services" >> .env
          echo "ENABLE_DRIZZLE_LOGGER=${{ secrets.ENABLE_DRIZZLE_LOGGER }}" >> .env
          echo "POSTGRES_DB_HOST=${{ secrets.POSTGRES_DB_HOST }}" >> .env
          echo "POSTGRES_DB_PORT=${{ secrets.POSTGRES_DB_PORT }}" >> .env
          echo "POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}" >> .env
          echo "POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> .env
          echo "POSTGRES_MAX_CONNECTIONS=${{ secrets.POSTGRES_MAX_CONNECTIONS }}" >> .env
          echo "GITHUB_CLIENT_ID=" >> .env
          echo "GITHUB_CLIENT_SECRET=" >> .env
          echo "GOOGLE_OAUTH_CLIENT_ID=" >> .env
          echo "GOOGLE_OAUTH_CLIENT_SECRET=" >> .env
          echo "GOOGLE_OAUTH_REDIRECT_URI=" >> .env
          echo "RESEND_API_KEY=" >> .env
          cat .env

      - name: Build and push Docker image for Linux
        uses: docker/build-push-action@v2
        continue-on-error: true
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/drewpayment/stacks:latest
          build-args: |
            ORIGIN=${{ secrets.ORIGIN }}

      # - name: Build and push Docker image for Apple Silicon
      #   uses: docker/build-push-action@v2
      #   continue-on-error: true
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/arm64
      #     push: true
      #     tags: ghcr.io/drewpayment/stacks:latest
