name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-ghcr-image:
    runs-on: ubuntu-latest
    
    env:
      ORIGIN: https://stacks.drewpayment.com
      ENABLE_DRIZZLE_LOGGER: ${{ secrets.ENABLE_DRIZZLE_LOGGER }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MYSQL_DB_HOST: aws.connect.psdb.cloud
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USER: ${{ secrets.MYSQL_DB_USER }}
      MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
      MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
      GITHUB_CLIENT_ID: ""
      GITHUB_CLIENT_SECRET: ""
      GOOGLE_OAUTH_CLIENT_ID: ""
      GOOGLE_OAUTH_CLIENT_SECRET: ""
      GOOGLE_OAUTH_REDIRECT_URI: ""
      RESEND_API_KEY: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for Linux
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/drewpayment/stacks:latest

      - name: Build and push Docker image for Apple Silicon
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/drewpayment/stacks:latest
